export const _REDUX_UPDATE_USERS_IN_RANGE = '_REDUX_UPDATE_USERS_IN_RANGE';
export const _REDUX_SET_USER_DATA = '_REDUX_SET_USER_DATA';
export const _REDUX_SET_CHAT = 'REDUX_SET_CHAT';
export const _REDUX_SET_FR = 'REDUX_SET_FR';
export const _REDUX_SET_MODAL = 'REDUX_SET_MODAL';
export const _REDUX_SET_TOAST = 'REDUX_SET_TOAST'