import Head from 'next/head';
import { useEffect } from 'react';
import Landing from '../components/Home';
import ResponsiveLayout from '../components/responsive-layout/Responsive';

export default function Home({ memory }) {
  useEffect(() => {
    console.log('State in Home', memory)
  })

  return (
    <>
      <Head>
        <title>Welcome to Proxy Chat!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout viewData={{ Landing: Landing }} />
    </>
  );
};
