import Head from 'next/head';
import Landing from '../components/Home';
import ResponsiveLayout from '../components/layouts/Responsive';



export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Proxy Chat!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout viewData={{ Landing: Landing }} />
    </>
  );
};
