import Head from 'next/head';
import { useEffect, useState } from 'react';
import Landing from '../components/Landing';
import ResponsiveLayout from '../components/responsive-layout/Responsive';
import auth from '../clientUtilities/auth';
import { useRouter } from 'next/router';
export default function Home({ memory }) {
  const router = useRouter();
  const [userID, setUserID] = useState(null);
  useEffect(() => {
    const loggedIn = auth.loggedIn();
    if (loggedIn) {
      const profile = auth.getProfile();
      setUserID(profile.data._id);
    } else {
      localStorage.removeItem('proxy_id_token');
    }
  });

  if (userID) router.push(`/proxy-chat/${userID}`);


  return (
    <>
      <Head>
        <title>Welcome to Proxy Chat!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout viewData={{ Landing: { Element: Landing }, display: 'single' }} />
    </>
  );
};
