export const _REDUX_UPDATE_INCOMING_REQUESTS = '_REDUX_UPDATE_INCOMING_REQUESTS'
export const _REDUX_SET_NOTIFICATION_LIST_VISIBILITY = 'REDUX_TOGGLE_NOTE_LIST'
export const _REDUX_UPDATE_USERS_IN_RANGE = '_REDUX_UPDATE_USERS_IN_RANGE';
export const _REDUX_UPDATE_FRIENDS_LIST = '_REDUX_UPDATE_FRIENDS_LIST';
export const _REDUX_SET_USER_DATA = '_REDUX_SET_USER_DATA';
export const _REDUX_SET_PICTURE = 'REDUX_SET_PICTURE';
export const _REDUX_SET_SOCKET = 'REDUX_SET_SOCKET';
export const _REDUX_SET_RANGE = 'REDUX_SET_RANGE';
export const _REDUX_SET_MODAL = 'REDUX_SET_MODAL';
export const _REDUX_SET_TOAST = 'REDUX_SET_TOAST';
export const _REDUX_SET_CHAT = 'REDUX_SET_CHAT';
export const _REDUX_SET_FR = 'REDUX_SET_FR';



